#Unit 3 Data Wrangling
#Experiment No.12
##Ayush Dumbre
##prn-25070123029 : A-2
##Title: To perform preprocessing on dataset & dealing with Missing Values

In [2]:
#missing values
import pandas as pd
import numpy as np
df1=pd.DataFrame({'c1':[11,21,np.nan],'c2':[15,np.nan,np.nan],'c3':[10,20,30]})
df1

     c1    c2  c3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [3]:
df1.isna()#boolen function

      c1     c2     c3
0  False  False  False
1  False   True  False
2   True   True  False

In [4]:
df1.isna().sum() #columnwise na values

c1    1
c2    2
c3    0
dtype: int64

In [5]:
df1.dropna() #NaN Rows are dropped

     c1    c2  c3
0  11.0  15.0  10

In [6]:
df1.fillna(value='DEFAULT')

        c1       c2  c3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [8]:
df1.fillna(df1.mean())#mean values of the columns are calculated

     c1    c2  c3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [9]:
df1.fillna(df1.median())#median values of the columns are calculated

     c1    c2  c3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [10]:
df1.fillna(df1.mode())#mode values of the columns are calculated

     c1    c2  c3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [34]:
#Preprocessing on Dataset-1
data={'rollno no':[101,102,103,104,105],'name':['raghav','rohan','neha','anik','arjit'],
      'age':[20,'-',21,22,21],'marks':[85,95,'-',88,76],'department':['CSE','IT','cse','IT','ENTC'],
      'admission_date':['01-06-2025','03-06-2025','04-06-2025','05-06-2025','06/06/2025']}
df=pd.DataFrame(data)
df
#saving as csv
df.to_csv('student_data.csv',index=False)

In [35]:
#step2: Replace '-' with NAN to mark missing values
df.replace('-',np.nan,inplace=True)
#convert columns to numeric where needed
df['age']=pd.to_numeric(df['age'],errors='coerce')
df['marks']=pd.to_numeric(df['marks'],errors='coerce')
df

/tmp/ipykernel_237/236870547.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('-',np.nan,inplace=True)

   rollno no    name   age  marks department admission_date
0        101  raghav  20.0   85.0        CSE     01-06-2025
1        102   rohan   NaN   95.0         IT     03-06-2025
2        103    neha  21.0    NaN        cse     04-06-2025
3        104    anik  22.0   88.0         IT     05-06-2025
4        105   arjit  21.0   76.0       ENTC     06/06/2025

In [36]:
#step3: check missing values
print("\nMissing Values")
print(df.isna().sum())

Missing Values
rollno no         0
name              0
age               1
marks             1
department        0
admission_date    0
dtype: int64

In [37]:
#Fill missing age with mean
df['age'].fillna(df['age'].mean(),inplace=True)
#Fill missing marks with median
df['marks'].fillna(df['marks'].median(),inplace=True)
df

/tmp/ipykernel_237/252562701.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace=True)
/tmp/ipykernel_237/252562701.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['marks'].fillna(df['marks'].median(),inplace=True)

   rollno no    name   age  marks department admission_date
0        101  raghav  20.0   85.0        CSE     01-06-2025
1        102   rohan  21.0   95.0         IT     03-06-2025
2        103    neha  21.0   86.5        cse     04-06-2025
3        104    anik  22.0   88.0         IT     05-06-2025
4        105   arjit  21.0   76.0       ENTC     06/06/2025

In [32]:
#step5: Fix inconsistent text formatting
df['department'] = df['department'].str.upper()
df['department']

0     CSE
1      IT
2     CSE
3      IT
4    ENTC
Name: department, dtype: object

In [38]:
#step6: Convert Admission date to standard datetime format
df['admission_date'] = pd.to_datetime(df['admission_date'],errors='coerce')
df['admission_date']

0   2025-01-06
1   2025-03-06
2   2025-04-06
3   2025-05-06
4          NaT
Name: admission_date, dtype: datetime64[ns]

In [39]:
#step7: Save cleaned dataset
df.to_csv("cleaned_student_data.csv",index=False)

In [55]:
#Upload the Dataset
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [56]:
df.isna().sum() #printing missing values

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [57]:
#imputing missing values
#1 Luggage Room
df['Luggage.room']=df['Luggage.room'].fillna(value=df['Luggage.room'].mean())
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room       0
dtype: int64

In [58]:
#2Rear seats
df['Rear.seat.room']=df['Rear.seat.room'].fillna(value=df['Rear.seat.room'].mean())
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     0
Luggage.room       0
dtype: int64

In [62]:
#3AirBags
df['AirBags']=df['AirBags'].fillna(df['AirBags'].mode().values[0])
df.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [63]:
#save cleaned dataset
df.to_csv('cleaned_cars_data.csv',index=False)